config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  get 'category' => 'main#category'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cron_running.rb
class CronRunning < ApplicationRecord
end

app/models/db.rb
module Db
  # def self.table_name_prefix
  #   'db_'
  # end
end

app/models/db/cron_running.rb
class Db::CronRunning < ActiveRecord::Base
end

app/models/db/hateb_rss.rb
class Db::HatebRss < ActiveRecord::Base
end

app/models/hateb.rb
class Hateb
  attr_reader :link, :category_ja, :category_en, :title, :bookmarkcount, :description
  attr_reader :org

  CATEGORY_JA = %w[世の中 政治と経済 暮らし 学び テクノロジー おもしろ エンタメ アニメとゲーム]
  CATEGORY_EN = %w[social economics life knowledge it fun entertainment game]

  CATEGORY_EN_TO_JA = Hash[*[CATEGORY_EN, CATEGORY_JA].transpose.flatten]
  CATEGORY_JA_TO_EN = Hash[*[CATEGORY_JA, CATEGORY_EN].transpose.flatten]

  def self.from_rss(item)
    category_ja = item.at("subject")&.text || "unknown"
    seed = {
      link: item.attr("rdf:about"),
      category_ja: category_ja,
      category_en: CATEGORY_JA_TO_EN[category_ja] || "unknown",
      title: item.at("title").text,
      bookmarkcount: item.at("bookmarkcount").text.to_i,
      description: item.at("description").text,
      org: item,
    }
    self.new(seed)
  end

  def self.from_db(item)
    seed = {
      link: item.link,
      category_ja: CATEGORY_EN_TO_JA[item.category] || "unknown",
      category_en: item.category,
      title: item.title,
      bookmarkcount: item.bookmarkcount,
      description: item.description,
      org: item,
    }
    self.new(seed)
  end

  def initialize(seed)
    @link = seed[:link]
    @category_ja = seed[:category_ja]
    @category_en = seed[:category_en]
    @title = seed[:title]
    @bookmarkcount = seed[:bookmarkcount]
    @description = seed[:description]
    @org = seed[:org]
  end

  def hateb_page_link
    # # TODO
    # if $is_from_smartphone
    #   "http://b.hatena.ne.jp/entry.touch/" + @link.sub(/^https?:\/\//, "")
    # else
    # "http://b.hatena.ne.jp/entry/" + @link.sub(/^https?:\/\//, "")
    # end
    url = "http://b.hatena.ne.jp/entry/"
    if @link.index('https://') == 0
      url << "s/"
    end
    url << @link.sub(/^https?:\/\//, "")
  end

  # TODO
  def yyyymmddhh
    @org.yyyymmddhh
  end
end

app/models/hateb_rss.rb
class HatebRss < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action do |controller|
    $is_from_smartphone = request.from_smartphone?
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    # ymdhs = ::CronRunning.order("id DESC").limit(2).map(&:yyyymmddhh)
    cron_runnings = ::CronRunning.order("id DESC").limit(2).to_a
    @croned_at = cron_runnings.first.updated_at

    @cache_key = @croned_at.to_s + (params[:category] || '')

    @rsses = Rails.cache.fetch(@cache_key) do
      ymdhs = cron_runnings.map(&:yyyymmddhh)
      now_ymdh, prev_ymdh = ymdhs
      if params[:category]
        rsses = ::HatebRss.where(category: params[:category], yyyymmddhh: ymdhs).map{|item| ::Hateb.from_db(item)}.group_by(&:yyyymmddhh)
      else
        rsses = ::HatebRss.where(yyyymmddhh: ymdhs).map{|item| ::Hateb.from_db(item)}.group_by(&:yyyymmddhh)
      end

      rss2 = []
      if rsses.has_key?(now_ymdh) && rsses.has_key?(prev_ymdh)
        rsses[now_ymdh].each do |now_rss|
          if prev_rss = rsses[prev_ymdh].find{|prev_rss| prev_rss.link == now_rss.link}
            rss2 << {
              diff_bookmarkcount: now_rss.bookmarkcount - prev_rss.bookmarkcount,
              rss: now_rss,
            }
          else
            rss2 << {
              diff_bookmarkcount: now_rss.bookmarkcount,
              rss: now_rss,
            }
          end
        end
      elsif rsses.has_key?(now_ymdh)
        rsses[now_ymdh].each do |now_rss|
          rss2 << {
            diff_bookmarkcount: now_rss.bookmarkcount,
            rss: now_rss,
          }
        end
      end
      rss2 = rss2.sort_by!{|rss| rss[:diff_bookmarkcount]}.reverse!.take(50)
      rss2.map do |rss|
        if rss[:diff_bookmarkcount] > 0
          rss[:diff_bookmarkcount_symbol] = "↑"
        elsif rss[:diff_bookmarkcount] == 0
          rss[:diff_bookmarkcount_symbol] = "→"
        else
          rss[:diff_bookmarkcount_symbol] = "↓"
        end
        rss
      end
    end
  end

  def category
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <title>はてブ毎時ランキング</title>
  <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no">
  <meta name="keywords" content="はてブ,毎時,ランキング">
  <meta name="description" content="はてなブックマーク数を毎時でランキングしています。">
  <%= stylesheet_link_tag 'application', media: 'all' %>
</head>
<body>
<%= yield %>
<footer>Created by <a href="http://profile.hatena.ne.jp/rightgo09/">rightgo09</a></footer>
</body>
</html>

app/views/main/category.html.erb
<% cache do %>
  <header>
    <h1><%= link_to('はてブ毎時ランキング', root_path) %></h1>
  </header>

  <h2>カテゴリ</h2>

  <ul>
    <li><%= link_to('一般', root_path) %></li>
    <% Hateb::CATEGORY_EN_TO_JA.each do |en, ja| %>
      <li><%= link_to(ja, root_path(category: en)) %></li>
    <% end %>
  </ul>
<% end %>

app/views/main/index.html.erb
<% cache @cache_key do %>

  <header>
    <div id="setting"><%= link_to('〓', category_path) %></div>
    <h1><%= link_to('はてブ毎時ランキング', root_path) %></h1>
    <div><small><%= @croned_at.strftime("%Y/%m/%d %H:%M") %> 更新</small></div>
  </header>

  <ol>
    <% @rsses.each do |rr| %>
      <% r = rr[:rss] %>
      <li class="entry">
        <div>
          <span class="ttl"><%= r.title %></span>
        </div>
        <div>
          <span class="lnk"><%= link_to(CGI.unescape(r.link), r.link, target: "_blank") %></span>
        </div>
        <div>
          <span class="bkcnt"><%= link_to(r.bookmarkcount.to_s + " users", r.hateb_page_link, target: "_blank") %></span>
          <span class="addbkcnt">(<%= rr[:diff_bookmarkcount_symbol] %><%= rr[:diff_bookmarkcount] %>)</span>
          <span class="category category-<%= r.category_en %>"><%= r.category_ja %></span>
          <% if r.bookmarkcount == rr[:diff_bookmarkcount] %>
              <span class="new">New!</span>
          <% end %>
        </div>
        <div class="dsc"><%= r.description %></div>
      </li>
    <% end %>
  </ol>

<% end %>

app/views/setting/index.html.erb
<header>
  <h1><%= link_to('はてブ毎時ランキング', root_path) %></h1>
</header>

<h2>カテゴリ</h2>

<ul>
  <li><%= link_to('一般', root_path) %></li>
  <% HatebRss::CATEGORY_EN_TO_JA.each do |en, ja| %>
    <li><%= link_to(ja, root_path(category: en)) %></li>
  <% end %>
</ul>